### ISSUE TITLE
alt er jævlig

### ISSUE THREAD

**Issue by espbard** [menneske2/Innlevering3#2]
hvor er nettsida???

**Comment by espbard** [comment]
Storm! faan åsså! Herre ska du som gruppeleder ta dæ av...

**Comment by StormOstberg** [comment]
Som prosjektleder kan jeg desværre ikke ta meg av dette, men henviser deg videre til vår tekniske avdeling

**Comment by espbard** [comment]
fuk u

**Comment by StormOstberg** [comment]
Hvis din holdning til kollegaer og overordnede ikke endrer seg i svært nær fremid vil du bli midlertidig suspandert. Eller eventuelt få nedsatt lønning i en utvidet periode.
Mvh. Prosjektleder

**Comment by espbard** [comment]
ur still a dick

**Comment by FredrikKvalheim** [comment]
#NotMyProjectLeader, jeg er Fredrik nr. 9/11

**Comment by zyrgel** [comment]
![](http://i.imgur.com/9JzZhEN.jpg)

**Comment by StormOstberg** [comment]
Da er det med stor sorg jeg må si at deres arbeid ikke vil bli betalt, og deres rettigheter til å motsi ledelsen fratas umiddelbart

**Comment by espbard** [comment]
fake news!!

**Comment by StormOstberg** [comment]
Espbard er bae! I rate 5/7!  I izt still dik...!

**Comment by menneske2** [comment]
Jeg er Fredrik nr. 420
